language: java

jdk:
    - openjdk8

cache:
    directories:
        - $HOME/.m2

before_install:
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install:
    - mvn --s .travis/settings.xml clean install -B -V

after_success:
    - bash <(curl -s https://codecov.io/bash)

deploy:
    provider: script
    script: bash .travis/deploy.sh
    on:
        branch: master
        condition: env(RELEASE) = true
