language: java

jdk:
    - openjdk8

before_install:
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install:
    - mvn --s .travis/settings.xml clean install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

deploy:
    provider: script
    script: bash .travis/deploy.sh
    on:
        branch: master
        condition: $RELEASE = true
